FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq5 postgresql-client && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "run.py"]
